import {
    AddOutlined,
    ContentCopyOutlined, 
    DarkModeOutlined, 
    DeleteOutlined, 
    EditOutlined, 
    LightModeOutlined, 
    LoginOutlined, 
    LogoutOutlined, 
    ErrorOutline, 
    WarningOutlined, 
    CheckCircleOutlineOutlined, 
    PersonOutlineOutlined, 
    PeopleOutlineOutlined,
    HelpOutlineOutlined,
    InfoOutlined,
    SendOutlined,
    MoreHorizOutlined,
    MoreVertOutlined,
    BackspaceOutlined,
    SaveOutlined,
    CreateNewFolder,
    DownloadOutlined,
    SummarizeOutlined,
    AttachFile,
    SearchOutlined,
    Mic,
    ImageOutlined,
    VolumeUpOutlined,
    VolumeDownOutlined,
    AssistantOutlined,
    KeyboardArrowDown,
    KeyboardArrowUp,
    KeyboardArrowLeft,
    KeyboardArrowRight,
    KeyboardDoubleArrowDown,
    KeyboardDoubleArrowUp,
    KeyboardDoubleArrowLeft,
    KeyboardDoubleArrowRight,
    Dashboard,
    Inventory,
    Factory,
    Warehouse,
    Receipt,
    ShoppingCart,
    AddShoppingCart,
    Settings,
    ImportExport,
    DataUsage,
    PictureAsPdf,
    Visibility,
    VisibilityOff,
    Refresh,
    AutoAwesome,
    FolderZip,
    TextSnippet,
    LocalOffer
} from "@mui/icons-material";

export const UniIcons = {
    DarkMode: DarkModeOutlined,
    LightMode: LightModeOutlined,
    Copy: ContentCopyOutlined,
    Add: AddOutlined,
    Delete: DeleteOutlined,
    Edit: EditOutlined,
    Logout: LogoutOutlined,
    Login: LoginOutlined,
    Error: ErrorOutline,
    Warning: WarningOutlined,
    Success: CheckCircleOutlineOutlined,
    Person: PersonOutlineOutlined,
    People: PeopleOutlineOutlined,
    Help: HelpOutlineOutlined,
    Info: InfoOutlined,
    Send: SendOutlined,
    HorizontalMenu: MoreHorizOutlined,
    VerticalMenu: MoreVertOutlined,
    Clear: BackspaceOutlined,
    Save: SaveOutlined,
    Create: CreateNewFolder,
    Download: DownloadOutlined,
    Summarize: SummarizeOutlined,
    Attachment: AttachFile,
    Search: SearchOutlined,
    Microphone: Mic,
    Image: ImageOutlined,
    VolumeUp: VolumeUpOutlined,
    VolumeDown: VolumeDownOutlined,
    Assistant: AssistantOutlined,
    Left: KeyboardArrowLeft,
    Right: KeyboardArrowRight,
    Up: KeyboardArrowUp,
    Down: KeyboardArrowDown,
    LeftDouble: KeyboardDoubleArrowLeft,
    RightDouble: KeyboardDoubleArrowRight,
    UpDouble: KeyboardDoubleArrowUp,
    DownDouble: KeyboardDoubleArrowDown,
    Dashboard: Dashboard,
    Inventory: Inventory,
    Factory: Factory,
    Warehouse: Warehouse,
    Receipt: Receipt,
    ShoppingCart: ShoppingCart,
    AddShoppingCart: AddShoppingCart,
    Settings: Settings,
    ImportExport: ImportExport,
    Usage: DataUsage,
    Pdf: PictureAsPdf,
    Visibility: Visibility,
    VisibilityOff: VisibilityOff,
    Refresh: Refresh,
    AI: AutoAwesome,
    Archive: FolderZip,
    Text: TextSnippet,
    Tag: LocalOffer
}

export default UniIcons